### ISSUE TITLE
issue when i try to chan release 

### ISSUE THREAD

**Issue by ghost** [geut/chan#5] opened 2017-06-15 13:56 UTC
Hi All ,
Im trying to use chan for changelog , all the commands are working perfectly till i enter "chan  release 1.0.0.1" , the error "Chan: The url must be a string." is raised .
Any help please

**Comment by elmasse** [comment] 2017-06-15 14:04
hello @ImadMaachari 
Can you provide which chan version are you using? And is your project under a git repository? (github or any other?) 


Thanks!

**Comment by tinchoz49** [comment] 2017-06-15 14:33
hi @ImadMaachari, how are you? The problem is because  `chan` by default try to create a tag compare of releases based on your github remote url. This is required to keep the standard of keep a changelog.

Something like this:
```
[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.3.0...HEAD
[0.3.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.2.0...v0.3.0
[0.2.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.1.0...v0.2.0
```

If your repository is behind another hosting you need to provide the url to compare the tags.

This is an example using bitbucket:

`chan release 1.0.0 --git-compare 'https://bitbucket.org/YOURPROJECT/compare/<from>..<to>'`

btw: `<from>` and `<to>` are necesary in the git-compare

**Comment by dpaez** [comment] 2017-06-15 15:12
Hello everybody, if @tinchoz49 is right (usually he is) this is not a chan error but nevertheless I think we can do it better and improve the error message to something more helpful.

**Comment by ImadMaachari** [comment] 2017-06-16 00:30
hi @elmasse , im using chan 1.3.0-1 . and im not using git for the example as im trying to include chan for my next projects , i think the error is due to not using git as @tinchoz49 mentioned . will try using git and let you know .
Thanks!

**Comment by tinchoz49** [comment] 2019-01-15 16:05
Fixed on the next [v2](https://github.com/geut/chan/tree/v2.0.0-beta) release.

**Comment by tinchoz49** [comment] 2019-04-17 18:37
closed by: https://github.com/geut/chan/pull/35

**Closed by tinchoz49** 2019-04-17 18:37 UTC
